### PR TITLE
IHStemplate. Merged and Resolved changes 

### PR DESCRIPTION
**Pull request by skounis**

### CODE REVIEW

**Comment by bernhard-da** [comment]
hi, thx for the contribution. just some quick remarks

- including `js/ihsn-style.js` for any style breaks (at least) hover over questionsmarks for non-IHSN styles
- could you please make sure, the ihsn-styles are only applied, if the theme is selected, eg by using two helper functions as below:

```
ihsn_theme_active <- function() {
  .guitheme=="ihsn-root.css"
}
set_class_if_ihsn <- function(ihsn_class="wb-btn-inline") {
  switch(ihsn_theme_active(), ihsn_class, NULL)
}
# example from ui_about.R
btn_credits <- bsButton("btn_credits", "here", style="primary", size="extra-small", class=set_class_if_ihsn("wb-btn-inline"))
```
- `man/.Rapp.history` is empty?

Please update the pull-request. In the meantime, I'll have a closer look at it.

**Comment by skounis** [comment]
@bernhard-da 

Thank you for this review. 

1. **We noted to work on that and load the `.js` file** of the theme ONLY when the there is selected.

- https://github.com/skounis/sdcMicro/issues/151

2. **Regarding the `set_class_if_ihsn()` method** do you believe that it is necessary? All the extra CSS classes are prefixed, `wn-*`,  so it is hardly possible to conflict with classes other theses are having instructions for. In addition to that HTML and the rendering engine of the browsers just ignores classes with no rules specified for them. This comes at no cost. 

Given that is it worth to apply the classes by using a method call `class=set_class_if_ihsn("wb-btn-inline")` ?

**Comment by bernhard-da** [comment]
hi, it is true that extra classes are prefixed, but the layout of other themes is still changed. thus I think it is a good idea to apply these extra classes only if the ihsn theme is used.

**Comment by skounis** [comment]
@bernhard-da Do we have cases where the layout of other themes is changed due to the extra classes. It is hardly possible for this to happen. 

If there are changes these are related to the changes in the markup the `R` produces. Style related information is pulled out from there. We have an open case on how to handle that.

Even if we remove the extra classes the style of the other themes will not change. 

It is a very common practice, in many frameworks, to have classes in the markup which provides the option for very details CSS selectors to be used.  These classes never affect the style of the pages. 

The primary purpose of these classes added is not to style the element but to describe them. In the future, other themes could make use of them. That's the strongest argument to let them there. We could discuss that further.

**Comment by bernhard-da** [comment]
hi  @skounis, thx for pointing that out. I just saw that for example the navigation bar using the yeti-theme looked differently, also some headers were differently aligned...

could it be that you're changing default (bootstrap?) values in some of the classes you've been adding which has these "side-effects" to the other themes?

**Comment by skounis** [comment]
@bernhard-da 

the navigation bar has style information defined inline with the markup up, a practice that limits the style options a new theme could adjust. We pulled them out. There is a work in progress to put them back, but not within the markup. We are preparing a .css file for yeti. When we finish we will share that with you.

**Comment by bernhard-da** [comment]
@skounis ok, I understand. 

The reason I am asking is that we do not what to have any issues or dependencies if - for some reason - the ishn-theme won't be updated. We want to make sure that we can - in such a case - just switch back to one of the bootswatch-default themes. Also, the issue with the navigation bar just struck me when I played around with the GUI for like two minutes, I didn't had time yet to do some further tests.

**Comment by skounis** [comment]
@bernhard-da rest assured. Extra classes will never create issues or dependencies. This about them and an improved way to describe your markup, regardless the theme that will make use of them.

For the navigation bar, this is a work in progress. I will keep you posted.

**Comment by bernhard-da** [comment]
thanks @skounis! this looks good for the yeti theme. could you please do the same as well for the other two themes (flatly and journal)? that would be perfekt.

btw, great job, new theme looks very good imo!

**Comment by skounis** [comment]
@bernhard-da I have scheduled that. I will keep you posted

**Comment by skounis** [comment]
@bernhard-da This PR is updated and now contains the adjustments for the Flatly and Journal themes

**Comment by bernhard-da** [comment]
hi @skounis, thx. I just played around with this for a while and I think it's very good. I'd ask you one more thing which is to rebase the pull request against the next-branch so that we can easily merge it to master and release a new version including the new theme soon.

**Pull request closed without merging**
