### PR TITLE
Set variable label to NA if value label

### PR DESCRIPTION
**Pull request by thijsbenschop**
read_dta uses the values labels as variable label if the variable label is absent
since the variable labels are a list of length more than one, this leads to errors later on

### CODE REVIEW

**Comment by thijsbenschop** [comment]
The problem is caused by the fact that read_dta saves the value labels both in the value label as well as in the variable label attribute in case a variable has value labels but no variable label. This is probably a rare case. In that case the value label is a list of length equal to the number of levels/value labels, which causes the error. Therefore, I check the length of the variable label and set the variable label to NA, if the length is longer than 1. The case we do not capture is a variable with one level/value label and no variable label. This won’t cause a technical problem (no error), but would be wrong. Instead of no variable label, we would have the first and only value label in this extremely unlikely case. We could check for this case by comparing the value and variable label and set to NA if both are the same.

Example files that cause this problem are on in the following folder on Box: Issues and suggestions sdcMicro\sdcGUI() - comments\Data\Test Unicode

**Comment by bernhard-da** [comment]
hi. is your latest comment on this issue something that is fixed with your pull request? since stata files have (as you know :) ) very little priority for us, I'd kindly ask you to update your pull request so that it fixes all these issues and tell me, when i look at it so i can review and merge it. thx.

**Comment by thijsbenschop** [comment]
Thanks, yes, all the described issues were addressed

**Comment by bernhard-da** [comment]
thx, merged.

**Pull request merged**
