### PR TITLE
Propose three new functions for handling STATA labels in GUI

### PR DESCRIPTION
**Pull request by thijsbenschop**
1) Function extractLabels: call in case STATA file is read
Add to GUIfunctions.R after line 324 (before converting to data.frame and convert class labelled to class factor)

Save label information for STATA files
```R
if (type == "stata") {
  lab <- extractLabels(res)
}
```
2) Function changeVarLabel: In the GUI, there should be a possibility to view all variable labels in a table and edit them.  For editing, this function should be called

3) Function addVarLabels: function to be run before exporting data if output file is STATA (after extracting manipulated data from sdcMicroObj)

4) Outstanding: function writeLabelDoFile: a function to collect the value labels and write a do file

### CODE REVIEW

**Comment by bernhard-da** [comment]
why is there a parameter `new` in `changeVarLabel()`? does not seem to be used.

**Comment by thijsbenschop** [comment]
Sorry, I forgot to remove this. At first I also had an option in this function to add labels to newly created variables. But since the only variables that can be newly created in the GUI are strata vars, this option wasn't so useful after all, so I decided to remove it. 

I fixed this in a new commit.

**Comment by thijsbenschop** [comment]
Hi, regarding the value labels: the factor levels are automatically exported as value labels. This covers in my opinion all cases we are interested in, so we don't need an additional function for that. I tested the following: loading a labeled file, making changes to the variables (e.g., recoding) and exporting. The new factor levels labels are correctly exported. In case of converting a numeric variable to a factor variable, this also works fine. The user can use the recoding function or 'modify an existing factor variable' function to change value labels or add value labels to newly created factor variables.

**Comment by bernhard-da** [comment]
perfect.

**Pull request merged**
