### PR TITLE
Function selectHouseholdData

### PR DESCRIPTION
**Pull request by thijsbenschop**
Created a function to extract household data from full dataset for treatment of household level data.

### CODE REVIEW

**Comment by bernhard-da** [comment]
Hi. Thx for your contribution. I would kindly ask you, to fix two issues with this commit.
- There is an error in the code itself. You are using an object `hhID` (it should be `hhId`) which has not been declared in `selectHouseholdData()`!
- I would also kindly ask you to come up with a solution for weights. Most of the time sampling weights are given on individual-level, so we need to come up with something to probably sum up the weight-variable (if available) on cluster-level e.g by adding additional parameters `weightVar` and `sumWeights` (which could be logical) or something like that. Because if we don't do this, we likely end up with wrong sampling weights.

You can just update the code in your forked repo and commit again. The pull request will automatically update!

**Comment by bernhard-da** [comment]
also some error checks would be nice, e.g make sure that all variables listed in `hhId` and `hhVars` are available in `dat`.

**Comment by thijsbenschop** [comment]
Thanks, I will do so. I thought about these checks, but since the function will mainly be used in the GUI, I assumed that the input cannot be wrong if selected in the GUI, e.g. the hhID can only be selected from the variables in the loaded dat.

**Comment by thijsbenschop** [comment]
I made some improvements to selectHouseholdData and committed them to my fork

**Comment by thijsbenschop** [comment]
And added the function to merge: mergeHouseholdData

**Comment by bernhard-da** [comment]
Hi. Thx for the update.

Just one comment. The more I think about the sampling weights on household level, the more I think your initial proposition was already what is needed. We just give the user the responsibility to specify an appropriate weight-variable (if any). Thus we do not have to try to do something to average individual level weights to aggregated weights. 

Perhaps the only "issue" was, that the example you choose to illustrate the function was not very good because you choose variable `sampling_weight` (individual level) when applying `selectHouseholdData()`.  In this special (and unrealistic) case in which all sampling_weights equal 100, each household would get a sampling weight of 100 which is very likely not intended.

What do you think about basically reverting the `selectHouseholdData()` function (removing the `weightType` argument and modify the example by setting `weightVar` to `NULL` and writing in the comment, that in this testdataset, no household weights are available. If such were available one would set `weightVar` to the appropriate variable?

**Comment by thijsbenschop** [comment]
Hi, thanks for your comments.

I agree that creating the appropriate household weight would be something the user can do in the software package of his choice. We can add a note in the help file and the GUI that the weight specified should be at the household level. for the example: the proposed function the household should divide the individual weight by the number of household members, e.g. a household with 4 members would get a weight of 100/4=25. Would it be an idea to add a household weight variable to the testdata dataset and specify this one. The household weights could be just 10 divided by the number of members in the household. Otherwise the help file and example might give the user the impression that there is no need for a weight.

**Comment by bernhard-da** [comment]
I updated the `testdata` dataset and added a variable calls `household_weights` which the computed according to your last suggestion.

I would thus propose to
- simplify `selectHouseholdData()` by removing the arguments `weightVar` and `weightType` again. The weight (if any) whould be listed within `hhVars`. In the example we can then use variable `household_weights` from `data(testdata)` for this issue
- simplify `mergeHouseholdData()` by removing argument `weightVarHH`
- update the example for `mergeHouseholdData()` for the intended usage by creating two problem instances with `createSdcObj()` (one with `testdata` directly, one with with household data extracted with `selectHouseholdData()`). Then apply any method to each problem, return for both the anonymized microdataset using `extractManipData()`  and finally demostrate how to merge these two anonymized datasets with `mergeHouseholdData()`.

I think these changes are fairly easy and we can then merge them and update the GUI. But for this task I'd rather open a new issue because we need (as already discussed) to specify where and how to put the "merge"-feature..

**Comment by thijsbenschop** [comment]
Hi, 

I just committed some changes to these two functions. I left the argument weightVar by renaming it to weightVarHH. In this way the user is made aware that it is important to use a household level weight. Also added a check whehther the weights are all the same within households, since this could mean that the user used individual weights. Of course this does not detect all misspecified weights.

**Comment by bernhard-da** [comment]
Hi. Thx for the nice updates. 

I have just another question before merging this. You mentioned in #105 that (in the first case of preparing data), users should be made aware that they should also select household weights. The question now is: Isn't this completely irrelevant because in the next logical step (creating an sdcObj), the user still can decide not to select a variable as weight-variable? 

So why not let the user (in `selectHouseholdData()`) select all variables he thinks are relevant for the household file (probably also add the note with regards to the weights) and then continue. In this case the distinction between variables and weight-variable is not important, we could also remove all the checks in `selectHouseholdData()` and give some responsibility to the user. We can't force them anyway to select weights when creating the problem instance (given that they even exist.)

**Pull request merged**
