### PR TITLE
Add error pop-up boxes

### PR DESCRIPTION
**Pull request by thijsbenschop**
Suggestion to add pop-up boxes for all error messages except for the initial one.

While working on my laptop with a smaller screen, I overlooked the error messages in the button below. Therefore , I made a suggestion to replace all error displayed in the button with pop-up messages with one exception, the initial error that no categorical key variables are selected. This way the user immediately has to correct a invalid selection and cannot lose track of where the error was made. What do you think of this?

### CODE REVIEW

**Comment by thijsbenschop** [comment]
PS: I noticed that my editor added some blanks and tabs to the code. If that is a problem, I can undo these changes.

**Comment by bernhard-da** [comment]
Hi, that would be indeed nice if you can revert the indentation and blanks. otherweise this looks good and I'll merge as soon as you've updated the pull request.

**Comment by thijsbenschop** [comment]
I think I reverted all automatic changes in the last commit.

**Comment by bernhard-da** [comment]
thx. is it possible that after line 622 a `return(modalDialog(...))` is missing?

**Comment by thijsbenschop** [comment]
Yep, thanks for noting, just added.

**Comment by bernhard-da** [comment]
thx. merged.

**Pull request merged**
