### PR TITLE
Change box direction and change definition of R_0, removed one box ca…

### PR DESCRIPTION
**Pull request by thijsbenschop**
…using problems

I experience problems with two boxes, which I both commented out now.
In line 272, I get this:
capture4
In lines 310-313, I get his:
capture3
What do I do wrong in the commented code such that the result are these boxes?

### CODE REVIEW

**Comment by bernhard-da** [comment]
Hi. the tooltip-text must not contain `'`-characters (but can contain `"`. I changed the tooltip for method `ROMM` and also moved the tooptip you in rankswap() for subset-mean preservation factor to the bottom. Please test, if everything works, we can close this without merging.

**Comment by thijsbenschop** [comment]
Ok, thanks for the advice. I don't see the tooltip for 'Select variables', which I commented out in lines 310-313 and I made one more change in line 390 on the definition of R_0

**Comment by bernhard-da** [comment]
updated.

**Comment by bernhard-da** [comment]
thx. merged.

**Pull request merged**
