### PR TITLE
Clean up shiny and DT namespace

### PR DESCRIPTION
**Pull request by schloerke**
Next version of `shiny` (1.4.0) is not (re)exporting the same functions as shiny v1.3.2.  By importing `shiny `as a package, rather than all of the methods individually, it allows us a little bit of freedom to change the exported api.

We are planning on releasing to CRAN here shortly.  If this change could be posted to CRAN soon, that would be great! (If not, please let us know. 😃 )

Thank you for your help!
\- Shiny Team

----------

My interpretation was the `shiny` methods were imported individually to avoid a namespace conflict with `DT`.  It appears that `DT` is only used for its two methods, so the package can be namespaced on the function call directly.

### CODE REVIEW

**Comment by bernhard-da** [comment]
hi @schloerke thx for the pr which i merge. the reason for explicitly importing all the shiny functions was because importing the entire package led to some conflicting warnings (in some old versions) that I can't reproduce any longer now :)

we'll probably add some little updates to the package and upload a new version to CRAN soon.

**Comment by schloerke** [comment]
Thank you! 

-------------------

Today I also learned (https://github.com/r-lib/roxygen2/issues/617#issuecomment-306048645 ) about using raw namespace to avoid the conflict.  This keeps it in line with the idea of "black listing" known conflicts, but importing everything else.
```r
#' @rawNamespace import(shiny, except=c(dataTableOutput, renderDataTable))
```

**Comment by bernhard-da** [comment]
@schloerke that's really great information! thx

**Comment by schloerke** [comment]
@bernhard-da `shiny` will be heading to CRAN today.  Without this change on CRAN, your package will not be able to install with the latest version of `shiny`.  Thank you for your help!

**Pull request merged**
