### PR TITLE
Improve factor to numeric conversion

### PR DESCRIPTION
**Pull request by thijsbenschop**
I noticed that the factor to numeric conversion for dataframes does not use the factor levels to create the numeric values. After loading HND_2012_L2L.dta and converting H65 to numeric, the variable contains the values 1 through 28, for the 28 factor levels. The suggestion convers the factro levels to numeric values, if the class of the variable is factor. In other cases nothing changes.

### CODE REVIEW

**Comment by bernhard-da** [comment]
This won't work for all factors, see for example the following factor:
```
a <- factor(1:5, levels=5:1, labels=LETTERS[5:1])
as.numeric(levels(a)[a]) 
[1] NA NA NA NA NA
```

**Comment by thijsbenschop** [comment]
Of course, if the levels aren't numeric, as in your example (A, B, C, D, E), this won't work. This is also the case for the levels "999,997 L or more", "Don't Know/Not Known" and "Refused/No response" in the Honduras example. Still, in the example dataset, I consider this result better than the one where I get the values 1-28. The question remains why you would like to convert a variable such as the one you show (A,B,C,D,E) to numeric? Isn't the situation in the Honduras file more likely to occur in a real file read in by read_dta? What do you think?

Alternatively, we could still introduce some condition, to check the result of as.numeric on the levels.

**Comment by cmachingauta** [comment]
Hi, the idea behind converting factor to numeric variables was so we could find a way to convert variables with numeric values like household id or income that may have been assigned the wrong variable type in data entry for example - without having to exit the sdcApp. Something that works the way stata's **destring** works and converts the variable type to numeric without distorting the actual values. I don't think it would be helpful to use it on non-numeric values.

**Comment by cmachingauta** [comment]
Hi, it might be helpful to also include a warning/tip that this feature is only added for convenience purposes and strictly recommended for use in cases where variables like hhid or weight were accidentally stored as factor and need to be numeric for the proper functioning of the process. We can work on the wording. For other situations we could suggest users use other packages and do it beforehand.

**Comment by bernhard-da** [comment]
@thijsbenschop i am still not sure if you suggestion is really an improvement because of the way factors are implemented in R (each level is assigned a number 1..N). the current implementation might have weaknesses, but I do not think it is a good idea to make decisions based on one variable in a specific data set. 

@cmachingauta I do not know `destring`, but if a factor has numeric values only (eg `factor(1:4)`, the current implementation will result in a numeric vector containing the corrent numbers. For any "special" cases I'd favor to ask the user to carefully prepare the input data.

**Comment by cmachingauta** [comment]
@bernhard-da, yes the current implementation works in that example factor(1:4), but the limitation comes when  the number assigned to each level does not correspond to the actual value in the variable as @thijsbenschop showed earlier. I agree that the user should be advised to very carefully prepare the input data. Just that improper classification is a common occurrence, and users may not always get everything perfectly prepared beforehand. If it can be implemented at all, just having the ability to convert a factor to numeric within the package would be a convenient and user friendly addition.

**Pull request merged**
