### PR TITLE
Text and layout changes

### PR DESCRIPTION
**Pull request by thijsbenschop**
Some layout changes and text edits for the GUI
Change labels of histograms
Remove steps and script after resetting microdata

I hope I didn't break anything while making the changes. If so, please let me know, so I can fix it

### CODE REVIEW

**Comment by bernhard-da** [comment]
hi, thx for the contribution. it probably will take a bit of time till I can have a look at it.

**Comment by bernhard-da** [comment]
just a quick question. since you've changed labels/texts, have you cross-checked with the sdcApp vignette?

**Comment by thijsbenschop** [comment]
I just did and updated the vignette

**Comment by bernhard-da** [comment]
thx, merged.

**Pull request merged**
