### PR TITLE
Text changes

### PR DESCRIPTION
**Pull request by thijsbenschop**
Added a additional info on the boxplot, what it actually shows. Especially the length of the whiskers isn't self-explanatory.

### CODE REVIEW

**Comment by thijsbenschop** [comment]
Commit 660b3dc is empty with no changes

**Comment by thijsbenschop** [comment]
Added text for tooltips on rank swapping. One question on the multivariate preservation factor. The help file states "Preserves the correlation between variables within a certain range based on the given constant R0. We can specify the preservation factor as R_0 = R_1/R_2 where R_1 is the correlation coefficient of the two fields after swapping, and R_2 is the correlation coefficient of the two fields before swapping." Since a range is mentioned and assuming R_1 < R_2 (loss of correlation), can I interpret R_0 as a lower bound for R_1/R_2, where 1 would be a natural upper bound?

**Comment by bernhard-da** [comment]
Hi, thx for the additions. 

I have just one further comment: If you change the labelling of any buttons or labels (headlines) of inputs, please also make sure that the changes (if any) are also made in the vignette on the GUI (`sdcGUI.rmd`). In this case, you changed the label of the `btn_rankswap` action button. thx.

To answer your question. I would also consider R_0 as a lower bound.

**Comment by thijsbenschop** [comment]
Thanks, I will make future changes also in the vignette.

I just noticed that the content of one box (the one for subset-mean preservation factor) is so large that the first lines are out of the browser window and therefore cannot be read. Is there a way to increase the width of the box for tipify? Alternatively, I can change placement to "bottom" for this one.

**Comment by bernhard-da** [comment]
thx. merged.

**Pull request merged**
